### ISSUE TITLE
Nodekit fail with some directory name

### ISSUE THREAD

**Issue by OlweCW** [small-tech/nodekit#4]
Hi I've discover something which look like a bug : 

If I create a project with a name containing dot, like "example.node.kit", nodekit fail to show me the page. To avoid that, I must change the name of the directory for a name without any dot. 

This is my first issue, so don't hesit to ask me to test some thing to help you, and sorry if this not how an issue must be writed.
![image](https://user-images.githubusercontent.com/45572222/152045670-9f759eb1-acfd-416b-ba78-c360f2b84cc7.png)

**Comment by aral** [comment]
@OlweCW Thank you for reporting this and apologies for the late reply.

I just checked with the latest version of NodeKit and it seems this is now working.

![image](https://user-images.githubusercontent.com/41798/171844079-78d8d715-6e1d-4ca9-ae6a-6a0554cd1b43.png)

Thanks again for taking the time to open an issue. I appreciate it :)
